// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Action", "Ease", "Fullscreen", "Mode", "Settings", "Storage"], function(Action, Ease, Fullscreen, Mode, Settings, Storage) {
    var Background, applyLightness, defaultLightness, lightness;
    defaultLightness = .7;
    lightness = defaultLightness;
    applyLightness = function() {
      return Action("Background:Lightness", Ease.linear(lightness, 0, 1, 0.25, 1));
    };
    if (Mode.background === true && Mode.settings) {
      lightness = +Storage("Background");
      if (isNaN(lightness)) {
        lightness = defaultLightness;
      }
      Settings.addSetting("Slider", 1, {
        name: "Background Color",
        value: lightness,
        snaps: [defaultLightness],
        update: function(v) {
          Storage("Background", lightness = v);
          return applyLightness();
        }
      });
    }
    Background = function() {
      if (Mode.background === "none") { // Special transparent mode for layering SVGA atop something else
        return Action("Background:Set", "transparent");
      } else if (typeof Mode.background === "string") { // Use a specific color
        return Action("Background:Set", Mode.background);
      } else if (Mode.background === true) { // Use lightness-based background
        return applyLightness(); // By default, make the background white
      } else {
        lightness = 1;
        return applyLightness();
      }
    };
    Make("Background", Background);
    // Run after the scene is ready, to set the initial color for ManifoldBackground
    return Take("SceneReady", Background);
  });

}).call(this);
