// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Action", "Settings", "SVG"], function(Action, Settings, SVG) {
    var Background, enterFullscreen, exitFullscreen, fullScreenSwitch, isFullscreen, switchChanged, update;
    // Break circular dependency
    Background = null;
    Take("Background", function(b) {
      return Background = b;
    });
    isFullscreen = function() {
      return (document.fullscreenElement != null) || (document.webkitFullscreenElement != null);
    };
    Make("Fullscreen", {
      active: isFullscreen
    });
    // If we support fullscreen in this browser, add a switch for it
    if (document.fullscreenEnabled || document.webkitFullscreenEnabled) {
      // We can't use the ?() shorthand for these functions because that doesn't work in Safari (possibly elsewhere)
      enterFullscreen = function() {
        if (SVG.svg.requestFullscreen != null) {
          return SVG.svg.requestFullscreen();
        }
        if (SVG.svg.webkitRequestFullscreen != null) {
          return SVG.svg.webkitRequestFullscreen();
        }
      };
      exitFullscreen = function() {
        if (document.exitFullscreen != null) {
          return document.exitFullscreen();
        }
        if (document.webkitExitFullscreen != null) {
          return document.webkitExitFullscreen();
        }
      };
      update = function(e) {
        // Make sure the switch matches the new state
        fullScreenSwitch.setValue(isFullscreen());
        return typeof Background === "function" ? Background() : void 0;
      };
      window.addEventListener("fullscreenchange", update);
      window.addEventListener("webkitfullscreenchange", update);
      // Whenever the switch state changes, update the fullscreen state to match
      switchChanged = function(switchActive) {
        if (switchActive === isFullscreen()) {

        // NOOP — the fullscreen state already matches the switch state
        } else if (switchActive) {
          return enterFullscreen();
        } else {
          return exitFullscreen();
        }
      };
      // Create the switch
      return fullScreenSwitch = Settings.addSetting("Switch", 5, {
        name: "Full Screen",
        value: false,
        update: switchChanged
      });
    }
  });

}).call(this);
