// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Action", "Settings"], function(Action, Settings) {
    var update;
    update = function(active) {
      return Action("Highlights:Set", active);
    };
    Settings.addSetting("Switch", 3, {
      name: "Highlights",
      value: true,
      update: update
    });
    return Take("AllReady", function() {
      return update(true);
    });
  });

}).call(this);
