// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Action", "Settings"], function(Action, Settings) {
    var update;
    update = function(active) {
      if (active) {
        return Action("Labels:Show");
      } else {
        return Action("Labels:Hide");
      }
    };
    Settings.addSetting("Switch", 4, {
      name: "Labels",
      value: true,
      update: update
    });
    return Take("AllReady", function() {
      return update(true);
    });
  });

}).call(this);
