// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Action", "ControlPanel", "Panel", "Reaction", "SVG", "SVGReady"], function(Action, ControlPanel, Panel, Reaction, SVG) {
    // It'd be better if this logic were in some sort of state machine with purview
    // over the entire GUI, but things aren't complex enough to warrant that yet.
    // Something like a router, I guess.
    Reaction("Panel:Hide", function() {
      return Panel.hide();
    });
    return Reaction("Panel:Show", function() {
      return Panel.show();
    });
  });

}).call(this);
