// Generated by CoffeeScript 2.7.0
(function() {
  (function() {
    var Config, defineProp;
    defineProp = function(obj, k) {
      return Object.defineProperty(obj, k, {
        get: function() {
          return Config[k];
        },
        set: function(v) {
          return Config[k] = v;
        }
      });
    };
    return Make("FlowArrows:Config", Config = {
      SCALE: 0.5, // Visible size of arrows is multiplied by this value — it's not factored in to any of the other size/distance/speed values
      SPACING: 600, // APPROXIMATELY how far apart should arrows be spaced? (+/-)50%
      FADE_LENGTH: 50, // Over how great a distance do Arrows fade in/out?
      MIN_SEGMENT_LENGTH: 200, // How long must a segment be before we put arrows on it?
      SPEED: 200, // The speed Arrows move per second when flow is 1
      MIN_EDGE_LENGTH: 8, // How long must an edge be to survive being culled?
      CONNECTED_DISTANCE: 1, // How close must two physically-disconnected points be to be treated as part of the same line?
      wrap: function(obj) {
        var k;
        for (k in Config) {
          if (k !== "wrap") {
            defineProp(obj, k);
          }
        }
        return obj; // Composable
      }
    });
  })();

}).call(this);
