// Generated by CoffeeScript 2.7.0
(function() {
  Take(["FlowArrows:Config", "FlowArrows:Process", "FlowArrows:Set", "Reaction", "Tick"], function(Config, Process, Set, Reaction, Tick) {
    var FlowArrows, enableAll, sets, visible;
    sets = [];
    visible = true; // Default to true, in case we don't have an arrows button
    enableAll = function() {
      var i, len, set;
      for (i = 0, len = sets.length; i < len; i++) {
        set = sets[i];
        set.enabled = visible;
      }
      return void 0;
    };
    Tick(function(time, dt) {
      var f, i, len, s, set;
      if (visible) {
        for (i = 0, len = sets.length; i < len; i++) {
          set = sets[i];
          if (set.parentScope.alpha > 0) {
            f = dt * Config.SPEED * FlowArrows.speed;
            s = Config.SCALE;
            set.update(f, s);
          }
        }
      }
      return void 0;
    });
    Reaction("FlowArrows:Show", function() {
      return enableAll(visible = true);
    });
    Reaction("FlowArrows:Hide", function() {
      return enableAll(visible = false);
    });
    FlowArrows = Config.wrap(function(parentScope, ...lineData) {
      var elm, set, setData;
      if (parentScope == null) {
        console.log(lineData);
        throw new Error("FlowArrows was called with a null target. ^^^ was the baked line data.");
      }
      elm = parentScope.element;
      // This removes invisible lines (which have a child named markerBox)
      if (elm.querySelector("[id^=markerBox]")) { // ^= matches values by prefix, so we can match IDs like markerBox_FL
        while (elm.hasChildNodes()) {
          elm.removeChild(elm.firstChild);
        }
      }
      setData = Process(lineData);
      set = Set(elm, setData);
      set.parentScope = parentScope;
      sets.push(set);
      return set;
    });
    // This is used by @debug.controls()
    FlowArrows.speed = 1;
    return Make("FlowArrows", FlowArrows);
  });

}).call(this);
