// Generated by CoffeeScript 2.7.0
(function() {
  Take(["FlowArrows:Config", "FlowArrows:Containerize", "FlowArrows:Segment"], function(Config, Containerize, Segment) {
    return Make("FlowArrows:Set", function(parentElm, setData) {
      return Containerize(parentElm, function(scope) { // This function must return an array of children
        var child, childName, i, j, len, results, segmentData;
        results = [];
        for (i = j = 0, len = setData.length; j < len; i = ++j) {
          segmentData = setData[i];
          if (segmentData.dist < Config.FADE_LENGTH * 2) {
            throw new Error(`You have a FlowArrows segment that is only ${Math.round(segmentData.dist)} units long, which is clashing with your fade length of ${Config.FADE_LENGTH} units. Please don't set MIN_SEGMENT_LENGTH less than FADE_LENGTH * 2.`);
          }
          childName = "segment" + i;
          child = Segment(scope.element, segmentData, childName, parentElm);
          results.push(scope[childName] = child);
        }
        return results;
      });
    });
  });

}).call(this);
