// Generated by CoffeeScript 2.7.0
(function() {
  // Config is defined in the config.coffee in every SVGA
  Take(["Config", "ParentData"], function(Config, ParentData) {
    var Mode, embedded, fetchAttribute, isDev;
    embedded = window !== window.top; // This logic needs to mirror the logic in ParentData
    fetchAttribute = function(name) {
      var val;
      if (embedded && (val = ParentData.get(name))) {
        if (val === "" || val === "true") {
          // This isn't ideal, but it is good enough for now
          return true;
        }
        if (val === "false") {
          return false;
        }
        if (val.charAt(0) === "{") {
          return JSON.parse(val);
        }
        return val;
      } else {
        return Config[name];
      }
    };
    isDev = function() {
      var loc, ref;
      loc = window.location;
      if (loc.search.indexOf("dev=false") > 0) {
        // Allow turning off dev mode when running locally
        return false;
      }
      if (loc.search.indexOf("dev=true") > 0) {
        // Allow turning on dev mode when running in prod
        return true;
      }
      // By default, dev mode is active when we have a URL with a port number
      return ((ref = loc.port) != null ? ref.length : void 0) >= 3;
    };
    Mode = {
      get: fetchAttribute,
      background: fetchAttribute("background"),
      dev: isDev(),
      noNavDbl: fetchAttribute("noNavDbl"),
      nav: fetchAttribute("nav"),
      embed: embedded,
      settings: fetchAttribute("settings")
    };
    if (Mode.embed) {
      // We always disallow nav in embed mode
      Mode.nav = false;
    }
    return Make("Mode", Mode);
  });

}).call(this);
