// Generated by CoffeeScript 2.7.0
(function() {
  (function() {
    var Convert, a, b, bs, mappings, q;
    mappings = {
      // Pressure
      psi: {
        kPa: 6.894757,
        bar: 0.06894757 // For bar, use metric units for all non-bar values
      },
      
      // Volume
      gal: {
        L: 3.7854 // US gallon
      },
      cc: {
        in3: 0.06102374
      },
      // Distance
      in: {
        mm: 25.4,
        cm: 2.54,
        m: 0.0254
      },
      // Area
      in2: {
        mm2: 645.16,
        cm2: 6.4516
      },
      // Weight
      lb: {
        kg: 0.4535924
      }
    };
    Convert = {};
    for (a in mappings) {
      bs = mappings[a];
      for (b in bs) {
        q = bs[b];
        (function(q) {
          (Convert[a] != null ? Convert[a] : Convert[a] = {})[b] = function(v) {
            return v * q;
          };
          return (Convert[b] != null ? Convert[b] : Convert[b] = {})[a] = function(v) {
            return v * 1 / q;
          };
        })(q);
      }
    }
    Convert.psi.kpa = function() {
      throw "You must use Convert.psi.kPa — with a capital P";
    };
    Convert.kpa = {
      psi: function() {
        throw "You must use Convert.kPa.psi — with a capital P";
      }
    };
    Convert.gal.l = function() {
      throw "You must use Convert.gal.L — with a capital L";
    };
    Convert.l = {
      gal: function() {
        throw "You must use Convert.L.gal — with a capital L";
      }
    };
    Convert.lbs = {
      kg: function() {
        throw "You must use Convert.lb.kg — lb is singular";
      }
    };
    Convert.kg.lbs = function() {
      throw "You must use Convert.kg.lb — lb is singular";
    };
    return Make("Convert", Convert);
  })();

}).call(this);
