// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Tick", "SVGReady"], function(Tick) {
    var avgList, avgWindow, fps, total;
    avgWindow = 1; // average over the past n seconds
    avgList = [];
    total = 0;
    fps = 1;
    Make("FPS", function() {
      return fps;
    });
    return Tick(function(time, dt) {
      avgList.push(dt);
      total += dt;
      while (total > avgWindow && avgList.length > 0) {
        total -= avgList.shift();
      }
      fps = avgList.length / total; // will be artifically low for the first second — that's fine
      if (isNaN(fps)) { // If we drop too low we get NaN — cap to 2
        return fps = 2;
      }
    });
  });

}).call(this);
