// Generated by CoffeeScript 2.7.0
(function() {
  Make("ScopeCheck", function(scope, ...props) {
    var i, len, prop;
    for (i = 0, len = props.length; i < len; i++) {
      prop = props[i];
      if (!(scope[prop] != null)) {
        continue;
      }
      console.log(scope.element);
      throw new Error(`^ @${prop} is a reserved name. Please choose a different name for your child/property \"${prop}\".`);
    }
    return void 0;
  });

}).call(this);
