// Generated by CoffeeScript 2.7.0
(function() {
  // This is a very minimal wrapper around localStorage.
  // You are expected to do your own type conversions when getting values back.
  var Storage;

  Make("Storage", Storage = function(k, v) {
    if (v != null) {
      return window.localStorage["SVGA-" + k] = v.toString();
    } else {
      return window.localStorage["SVGA-" + k];
    }
  });

}).call(this);
