// Generated by CoffeeScript 2.7.0
(function() {
  Take("Registry", function(Registry) {
    var Symbol;
    Symbol = function(symbolName, instanceNames, symbol) {
      var i, instanceName, len;
      symbol.symbolName = symbolName;
      Registry.set("Symbols", symbolName, symbol);
      for (i = 0, len = instanceNames.length; i < len; i++) {
        instanceName = instanceNames[i];
        Registry.set("SymbolNames", instanceName, symbol);
      }
      return void 0;
    };
    Symbol.forSymbolName = function(symbolName) {
      return Registry.get("Symbols", symbolName);
    };
    Symbol.forInstanceName = function(instanceName) {
      return Registry.get("SymbolNames", instanceName);
    };
    return Make("Symbol", Symbol);
  });

}).call(this);
