// Generated by CoffeeScript 2.7.0
(function() {
  Take([], function() {
    var Vec;
    return Make("Vec", Vec = {
      angle: function(a, b) {
        return Math.atan2(b.y - a.y, b.x - a.x);
      },
      distance: function(a, b) {
        var dx, dy;
        dx = b.x - a.x;
        dy = b.y - a.y;
        return Math.sqrt(dx * dx + dy * dy);
      }
    });
  });

}).call(this);
