// Generated by CoffeeScript 2.7.0
(function() {
  Take("Tween", function(Tween) {
    return Make("Wait", function(delay, next) {
      return Tween(0, 0, 0, {
        delay: delay,
        then: next
      });
    });
  });

}).call(this);
