// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Pressure", "Reaction", "Symbol"], function(Pressure, Reaction, Symbol) {
    return Symbol("BackgroundCover", [], function(svgElement) {
      var scope;
      return scope = {
        setup: function() {
          return Reaction("Background:Set", function(v) {
            return scope.fill = v;
          });
        }
      };
    });
  });

}).call(this);
