// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Pressure", "Symbol"], function(Pressure, Symbol) {
    return Symbol("HydraulicField", [], function(svgElement) {
      var scope;
      return scope = {
        setup: function() {
          var isInsideOtherField, p;
          isInsideOtherField = false;
          p = this.parent;
          while ((p != null) && !isInsideOtherField) {
            isInsideOtherField = p._symbol === this._symbol;
            p = p.parent;
          }
          if (!isInsideOtherField) {
            return this.pressure = 0;
          }
        }
      };
    });
  });

}).call(this);
