// Generated by CoffeeScript 2.7.0
(function() {
  Take(["FPS", "HUD", "Mode", "Tick", "SVGReady"], function(FPS, HUD, Mode, Tick) {
    if (!Mode.dev) {
      return;
    }
    return Tick(function() {
      var color, fps, fpsDisplay;
      fps = FPS();
      fpsDisplay = fps < 30 ? fps.toFixed(1) : Math.round(fps);
      color = fps <= 30 ? "#C00" : fps <= 50 ? "#E608" : "#0003";
      return HUD("FPS", fpsDisplay, color);
    });
  });

}).call(this);
