// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Action", "Ease", "Reaction", "SVG"], function(Action, Ease, Reaction, SVG) {
    Reaction("Background:Set", function(v) {
      SVG.style(document.body, "background-color", v);
      // We need to give the SVG element a background color,
      // or else the background will be black when fullscreen
      return SVG.style(SVG.svg, "background-color", v);
    });
    return Reaction("Background:Lightness", function(v) {
      var hue;
      hue = Ease.linear(v, 0, 1, 227, 218);
      return Action("Background:Set", `hsl(${hue}, 5%, ${v * 100 | 0}%)`);
    });
  });

}).call(this);
