// Generated by CoffeeScript 2.7.0
(function() {
  Take(["DOOM", "GUI", "Resize", "SVG", "Wait", "SVGReady"], function(DOOM, GUI, Resize, SVG, Wait) {
    var Banner, foreignObject, inner, outer;
    foreignObject = SVG.create("foreignObject", GUI.elm, {
      id: "svga-banner"
    });
    outer = DOOM.create("div", foreignObject, {
      id: "svga-banner-outer"
    });
    inner = DOOM.create("div", outer, {
      id: "svga-banner-inner"
    });
    Resize(function() {
      return SVG.attrs(foreignObject, {
        width: window.innerWidth,
        height: window.innerHeight
      });
    });
    Banner = function(html, time) {
      DOOM(inner, {
        innerHTML: html
      });
      DOOM(outer, {
        opacity: 1
      });
      if (time != null) {
        return Wait(time, Banner.hide);
      }
    };
    Banner.hide = function() {
      return DOOM(outer, {
        opacity: 0
      });
    };
    return Make("Banner", Banner);
  });

}).call(this);
