// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Mode"], function(Mode) {
    if (!Mode.dev) {
      // Disable the content menu, so that we can use long-press on touch Windows for pushButtons
      window.addEventListener("contextmenu", function(e) {
        return e.preventDefault();
      });
    }
    // Block drag-to-copy on Windows
    window.addEventListener("dragstart", function(e) {
      return e.preventDefault();
    });
    if (Mode.nav) {
      // Block scrolling on desktops
      window.addEventListener("scroll", function(e) {
        return e.preventDefault();
      });
      // Block scrolling on iOS
      return window.addEventListener("touchmove", function(e) {
        return e.preventDefault();
      });
    }
  });

}).call(this);
