// Generated by CoffeeScript 2.7.0
(function() {
  // The SVG starts off hidden. We unhide it when the time comes.
  Take(["Mode", "RAF", "SVG", "Tween", "AllReady"], function(Mode, RAF, SVG, Tween) {
    if (Mode.dev) {
      return RAF(function() {
        return SVG.svg.style.opacity = 1;
      });
    } else {
      return Tween(0, 1, .5, function(v) {
        return SVG.svg.style.opacity = v;
      });
    }
  });

}).call(this);
