// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Ease", "Registry", "ScopeCheck", "SVG"], function(Ease, Registry, ScopeCheck, SVG) {
    return Registry.add("ScopeProcessor", function(scope) {
      var alpha, element, placeholder;
      ScopeCheck(scope, "alpha");
      element = scope.element;
      placeholder = SVG.create("g");
      alpha = 1;
      return Object.defineProperty(scope, 'alpha', {
        get: function() {
          return alpha;
        },
        set: function(val) {
          if (val === true) {
            val = 1;
          }
          if (!val) {
            val = 0;
          }
          if (alpha !== val) {
            SVG.style(element, "opacity", alpha = Ease.clip(val));
            if (alpha > 0) {
              if (placeholder.parentNode != null) {
                return placeholder.parentNode.replaceChild(element, placeholder);
              }
            } else {
              if (element.parentNode != null) {
                return element.parentNode.replaceChild(placeholder, element);
              }
            }
          }
        }
      });
    });
  });

}).call(this);
