// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Registry", "ScopeCheck", "SVG"], function(Registry, ScopeCheck, SVG) {
    return Registry.add("ScopeProcessor", function(scope) {
      var paths;
      ScopeCheck(scope, "dash");
      paths = scope.element.querySelectorAll("path");
      scope.dash = function(v) {
        var i, len, path;
        for (i = 0, len = paths.length; i < len; i++) {
          path = paths[i];
          SVG.attrs(path, {
            "stroke-dasharray": v
          });
        }
        return void 0;
      };
      scope.dash.manifold = function() {
        return scope.dash("50 5 10 5 10 5");
      };
      return scope.dash.pilot = function() {
        return scope.dash("6 6");
      };
    });
  });

}).call(this);
