// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Mode", "Registry", "ScopeCheck", "Scope", "SVG"], function(Mode, Registry, ScopeCheck, Scope, SVG) {
    return Registry.add("ScopeProcessor", function(scope) {
      ScopeCheck(scope, "debug");
      return Object.defineProperty(scope, 'debug', {
        get: function() {
          return {
            controls: function() {
              var Control;
              Control = Take("Control");
              Control.slider({
                name: "Speed",
                group: "#f70",
                value: 1,
                change: (v) => {
                  var ref, ref1, ref2, ref3;
                  v = v === 0 ? 0 : Math.pow(500, v) / 500;
                  if ((ref = scope.rawTick) != null) {
                    ref.speed(v);
                  }
                  if ((ref1 = scope.tick) != null) {
                    ref1.speed(v);
                  }
                  if ((ref2 = scope.ms) != null) {
                    ref2.speed(v);
                  }
                  return (ref3 = Take("FlowArrows")) != null ? ref3.speed = 0.005 + v * 0.995 : void 0;
                }
              });
              return Control.button({
                name: "Step",
                group: "#f70",
                click: () => {
                  var ref, ref1, ref2;
                  if ((ref = scope.rawTick) != null) {
                    ref.step();
                  }
                  if ((ref1 = scope.tick) != null) {
                    ref1.step();
                  }
                  return (ref2 = scope.ms) != null ? ref2.step() : void 0;
                }
              });
            },
            point: function(color) {
              var point;
              if (Mode.dev) {
                point = Scope(SVG.create("g", scope.element));
                if (color != null) {
                  SVG.create("rect", point.element, {
                    fill: "#000",
                    x: 0,
                    y: 0,
                    width: 10,
                    height: 10
                  });
                }
                if (color != null) {
                  SVG.create("rect", point.element, {
                    fill: color,
                    x: 0,
                    y: 0,
                    width: 9,
                    height: 9
                  });
                }
                SVG.create("rect", point.element, {
                  fill: "#000",
                  x: -1,
                  y: -1,
                  width: 2,
                  height: 2
                });
                SVG.create("rect", point.element, {
                  fill: "#FFF",
                  x: -.5,
                  y: -.5,
                  width: 1,
                  height: 1
                });
                SVG.create("rect", point.element, {
                  fill: "#FFF",
                  x: 1,
                  y: -1,
                  width: 48,
                  height: 2
                });
                SVG.create("rect", point.element, {
                  fill: "#F00",
                  x: 1,
                  y: -.5,
                  width: 48,
                  height: 1
                });
                SVG.create("rect", point.element, {
                  fill: "#000",
                  x: -1,
                  y: 1,
                  width: 2,
                  height: 48
                });
                SVG.create("rect", point.element, {
                  fill: "#0F0",
                  x: -.5,
                  y: 1,
                  width: 1,
                  height: 48
                });
                return point;
              } else {
                "Warning: @debug.point() is disabled unless you're in dev";
                return {};
              }
            }
          };
        }
      });
    });
  });

}).call(this);
