// Generated by CoffeeScript 2.7.0
(function() {
  // This is a special scope processor just for controls,
  // allowing them to be enabled and disabled by animation code.
  Take(["Registry", "ScopeCheck", "SVG"], function(Registry, ScopeCheck, SVG) {
    return Registry.add("ScopeProcessor", function(scope, props) {
      var enabled;
      if (!props._isControl) {
        return;
      }
      ScopeCheck(scope, "enabled");
      enabled = true;
      Object.defineProperty(scope, 'enabled', {
        get: function() {
          return enabled;
        },
        set: function(val) {
          var ref;
          if (enabled !== val) {
            enabled = val;
            if ((ref = scope.input) != null) {
              ref.enable(enabled);
            }
            if (enabled) {
              scope.alpha = 1;
              return SVG.attrs(scope.element, {
                disabled: null
              });
            } else {
              scope.alpha = 0.3;
              return SVG.attrs(scope.element, {
                disabled: ""
              });
            }
          }
        }
      });
      if (props.enabled === false) {
        return scope.enabled = false;
      }
    });
  });

}).call(this);
