// Generated by CoffeeScript 2.7.0
(function() {
  // scope.ms
  // An every-frame update function that can be turned on and off by the content creator.
  // The frame rate is capped to 1000 Hz but otherwise approximates display refresh rate.
  Take(["Registry", "Tick"], function(Registry, Tick) {
    var speed;
    speed = 1;
    return Registry.add("ScopeProcessor", function(scope) {
      var acc, count, ms, running, step;
      if (scope.ms == null) {
        return;
      }
      running = true;
      acc = 0;
      count = 0;
      step = 1 / 1000;
      // Replace the actual scope ms function with a warning
      ms = scope.ms;
      scope.ms = function() {
        throw new Error("@ms() is called by the system. Please don't call it yourself.");
      };
      scope.ms.start = function() {
        return running = true;
      };
      scope.ms.stop = function() {
        return running = false;
      };
      scope.ms.toggle = function() {
        if (running) {
          return scope.ms.stop();
        } else {
          return scope.ms.start();
        }
      };
      scope.ms.restart = function() {
        acc = 0;
        return count = 0;
      };
      scope.ms.speed = function(s) {
        if (s != null) {
          speed = s;
        }
        return speed;
      };
      scope.ms.step = function() {
        count++;
        return ms.call(scope, count * step, step);
      };
      // Store a secret copy of the real ms function, so that warmup can use it
      scope._ms = function(time, dt) {
        var results;
        if (!running) {
          return;
        }
        acc += dt * speed;
        results = [];
        while (acc > step && running) {
          acc -= step;
          results.push(scope.ms.step());
        }
        return results;
      };
      return Tick(scope._ms);
    });
  });

}).call(this);
