// Generated by CoffeeScript 2.7.0
(function() {
  // Depends on style
  Take(["Registry", "ScopeCheck", "SVG"], function(Registry, ScopeCheck, SVG) {
    return Registry.add("ScopeProcessor", function(scope) {
      var accessors, enabled;
      ScopeCheck(scope, "pointerEvents");
      enabled = true;
      accessors = {
        get: function() {
          return enabled;
        },
        set: function(val) {
          enabled = val;
          return SVG.style(scope.element, "pointer-events", enabled ? null : "none");
        }
      };
      return Object.defineProperty(scope, "pointerEvents", accessors);
    });
  });

}).call(this);
