// Generated by CoffeeScript 2.7.0
(function() {
  // Depends on style
  Take(["Pressure", "Registry", "ScopeCheck", "SVG"], function(Pressure, Registry, ScopeCheck, SVG) {
    return Registry.add("ScopeProcessor", function(scope) {
      var accessors, pressure;
      ScopeCheck(scope, "pressure");
      pressure = null;
      accessors = {
        get: function() {
          return pressure;
        },
        set: function(val) {
          if (pressure !== val) {
            pressure = val;
            if (scope._setColor != null) {
              return scope._setColor(pressure);
            } else {
              return scope.fill = Pressure(scope.pressure);
            }
          }
        }
      };
      return Object.defineProperty(scope, "pressure", accessors);
    });
  });

}).call(this);
