// Generated by CoffeeScript 2.7.0
(function() {
  // This processor depends on the Style processor
  Take(["Registry", "ScopeCheck", "Tween"], function(Registry, ScopeCheck, Tween) {
    return Registry.add("ScopeProcessor", function(scope) {
      var tick;
      ScopeCheck(scope, "show", "hide");
      tick = function(v) {
        return scope.alpha = v;
      };
      scope.show = function(duration = 1, target = 1) {
        return Tween(scope.alpha, target, duration, {
          tick: tick,
          ease: "linear"
        });
      };
      return scope.hide = function(duration = 1, target = 0) {
        return Tween(scope.alpha, target, duration, {
          tick: tick,
          ease: "linear"
        });
      };
    });
  });

}).call(this);
