// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Registry", "ScopeCheck", "SVG"], function(Registry, ScopeCheck, SVG) {
    return Registry.add("ScopeProcessor", function(scope) {
      var alignment, element, text, textElement;
      ScopeCheck(scope, "text");
      element = scope.element;
      textElement = element.querySelector("tspan") || element.querySelector("text");
      text = textElement != null ? textElement.textContent : void 0;
      alignment = "left";
      Object.defineProperty(scope, 'align', {
        get: function() {
          return alignment;
        },
        set: function(val) {
          if (textElement == null) {
            throw new Error(`You have ${scope.id}.align = '${val}', but this scope doesn't contain any text or tspan elements.`);
          }
          if (alignment !== val) {
            alignment = val;
            return SVG.attr(textElement, "textAnchor", val === "left" ? "start" : val === "center" ? "middle" : "end");
          }
        }
      });
      return Object.defineProperty(scope, 'text', {
        get: function() {
          return text;
        },
        set: function(val) {
          if (textElement == null) {
            throw new Error(`You have ${scope.id}.text = '${val}', but this scope doesn't contain any text or tspan elements.`);
          }
          if (text !== val) {
            return SVG.attr(textElement, "textContent", text = val);
          }
        }
      });
    });
  });

}).call(this);
