// Generated by CoffeeScript 2.7.0
(function() {
  // Depends on style
  Take(["Voltage", "Registry", "ScopeCheck", "SVG"], function(Voltage, Registry, ScopeCheck, SVG) {
    return Registry.add("ScopeProcessor", function(scope) {
      var accessors, voltage;
      ScopeCheck(scope, "voltage");
      voltage = null;
      accessors = {
        get: function() {
          return voltage;
        },
        set: function(val) {
          if (voltage !== val) {
            voltage = val;
            if (scope._setColor != null) {
              return scope._setColor(voltage);
            } else {
              return scope.fill = Voltage(scope.voltage);
            }
          }
        }
      };
      return Object.defineProperty(scope, "voltage", accessors);
    });
  });

}).call(this);
