// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Input", "Mode", "Nav"], function(Input, Mode, Nav) {
    var blockDbl, calls, down, drag, dragging, up, wheel;
    if (!Mode.nav) {
      return;
    }
    dragging = false;
    down = function(e) {
      e.preventDefault(); // Without this, shift-drag pans the ENTIRE SVG! What the hell?
      if (Nav.eventInside(e)) {
        return dragging = true;
      }
    };
    drag = function(e, state) {
      if (dragging && state.down) {
        return Nav.by({
          x: state.deltaX,
          y: state.deltaY
        });
      }
    };
    up = function() {
      return dragging = false;
    };
    calls = {
      down: down,
      downOther: down,
      drag: drag,
      dragOther: drag,
      up: up,
      upOther: up
    };
    Input(document, calls, true, false);
    if (!Mode.noNavDbl) {
      blockDbl = function(elm) {
        while ((elm != null) && elm !== document) {
          if (elm.hasAttribute("block-dbl")) {
            return elm;
          }
          elm = elm.parentNode;
        }
        return null;
      };
      document.addEventListener("dblclick", function(e) {
        if (e.button !== 0) {
          return;
        }
        if (blockDbl(e.target)) {
          return;
        }
        if (Nav.eventInside(e)) {
          e.preventDefault();
          return Nav.to({
            x: 0,
            y: 0,
            z: 0
          });
        }
      });
    }
    wheel = function(e) {
      if (e.button !== 0) {
        return;
      }
      if (Nav.eventInside(e)) {
        e.preventDefault();
        if (e.deltaMode === WheelEvent.DOM_DELTA_PIXEL) {
          return Nav.by({
            z: -e.deltaY / 500
          });
        } else {
          return Nav.by({
            z: -e.deltaY / 20
          });
        }
      }
    };
    // Old code which was nice but sucked with mice
    // # Is this a pixel-precise input device (eg: magic trackpad)?
    // if e.deltaMode is WheelEvent.DOM_DELTA_PIXEL
    //   if e.ctrlKey # Chrome, pinch to zoom
    //     Nav.by z: -e.deltaY / 100
    //   else if e.metaKey # Other browsers, meta+scroll to zoom
    //     Nav.by z: -e.deltaY / 200
    //   else
    //     Nav.by
    //       x: -e.deltaX
    //       y: -e.deltaY
    //       z: -e.deltaZ

    // # This is probably a scroll wheel # DOESN'T WORK! :(
    // else
    //   Nav.by z: -e.deltaY / 500
    return document.addEventListener("wheel", wheel, {
      passive: false
    });
  });

}).call(this);
