// Generated by CoffeeScript 2.7.0
(function() {
  (function() {
    var Resize, cbs;
    cbs = [];
    Resize = function(cb) {
      return cbs.push(cb);
    };
    Resize._fire = function(info) {
      var cb, i, len;
      for (i = 0, len = cbs.length; i < len; i++) {
        cb = cbs[i];
        cb(info);
      }
      return void 0;
    };
    return Make("Resize", Resize);
  })();

}).call(this);
