// Generated by CoffeeScript 2.7.0
(function() {
  Take(["GUI", "Registry", "SVG"], function({
      ControlPanel: GUI
    }, Registry, SVG) {
    return Registry.set("Control", "divider", function(elm, props) {
      throw "Error: Control.divider() has been removed.";
    });
  });

}).call(this);
