// Generated by CoffeeScript 2.7.0
(function() {
  Take(["Registry", "GUI", "Scope", "SVG"], function(Registry, {
      ControlPanel: GUI
    }, Scope, SVG) {
    return Registry.set("Control", "label", function(elm, props) {
      var height, label, labelFill, labelY, scope;
      // Remember: SVG text element position is ALWAYS relative to the text baseline.
      // So, we position our baseline a certain distance from the top, based on the font size.
      labelY = GUI.labelPad + (props.fontSize || 16) * 0.75; // Lato's baseline is about 75% down from the top of the caps
      height = GUI.labelPad + (props.fontSize || 16);
      labelFill = props.fontColor || "hsl(220, 10%, 92%)";
      label = SVG.create("text", elm, {
        textContent: props.name,
        x: GUI.colInnerWidth / 2,
        y: labelY,
        fontSize: props.fontSize || 16,
        fontWeight: props.fontWeight || "normal",
        fontStyle: props.fontStyle || "normal",
        fill: labelFill
      });
      return scope = {
        height: height
      };
    });
  });

}).call(this);
