// Generated by CoffeeScript 2.7.0
(function() {
  Take(["GUI", "Input", "SVG", "Tween"], function({
      ControlPanel: GUI
    }, Input, SVG, Tween) {
    var active;
    active = null;
    return Make("PopoverButton", function(elm, props) {
      var activeBG, attachClick, bg, blueBG, click, curBG, handlers, highlighting, input, isActive, label, labelFill, orangeBG, scope, tickBG, toActive, toClicking, toHover, toNormal, unclick, whiteBG;
      handlers = [];
      isActive = false;
      highlighting = false;
      labelFill = props.fontColor || "hsl(227, 16%, 24%)";
      // Enable pointer cursor, other UI features
      SVG.attrs(elm, {
        ui: true
      });
      bg = SVG.create("rect", elm, {
        width: GUI.colInnerWidth - GUI.panelPadding * 2,
        height: GUI.unit,
        rx: GUI.groupBorderRadius
      });
      label = SVG.create("text", elm, {
        x: GUI.colInnerWidth / 2 - GUI.panelPadding,
        y: (props.fontSize || 16) + GUI.unit / 5,
        textContent: props.name,
        fill: labelFill,
        fontSize: props.fontSize || 16,
        fontWeight: props.fontWeight || "normal",
        fontStyle: props.fontStyle || "normal"
      });
      // Setup the bg stroke color for tweening
      curBG = null;
      whiteBG = {
        h: 220,
        s: 10,
        l: 92
      };
      blueBG = {
        h: 215,
        s: 100,
        l: 86
      };
      orangeBG = {
        h: 43,
        s: 100,
        l: 59
      };
      activeBG = {
        h: 92,
        s: 46,
        l: 57
      };
      tickBG = function(_curBG) {
        curBG = _curBG;
        if (highlighting && isActive) {
          return SVG.attrs(bg, {
            fill: "url(#MidHighlightGradient)"
          });
        } else {
          return SVG.attrs(bg, {
            fill: `hsl(${curBG.h | 0},${curBG.s | 0}%,${curBG.l | 0}%)`
          });
        }
      };
      tickBG(whiteBG);
      // Input event handling
      toNormal = function(e, state) {
        return Tween(curBG, whiteBG, .2, {
          tick: tickBG
        });
      };
      toHover = function(e, state) {
        if (!state.touch && !isActive) {
          return Tween(curBG, blueBG, 0, {
            tick: tickBG
          });
        }
      };
      toClicking = function(e, state) {
        return Tween(curBG, orangeBG, 0, {
          tick: tickBG
        });
      };
      toActive = function(e, state) {
        return Tween(curBG, activeBG, .2, {
          tick: tickBG
        });
      };
      unclick = function() {
        toNormal();
        return isActive = false;
      };
      click = function(e, state) {
        var handler, i, len;
        props.setActive(props, unclick);
        isActive = true;
        toActive();
        if (e !== false) {
          for (i = 0, len = handlers.length; i < len; i++) {
            handler = handlers[i];
            handler();
          }
        }
        return void 0;
      };
      input = Input(elm, {
        moveIn: function(e, state) {
          if (!isActive) {
            return toHover(e, state);
          }
        },
        dragIn: function(e, state) {
          if (state.clicking && !isActive) {
            return toClicking(e, state);
          }
        },
        down: function(e, state) {
          if (!isActive) {
            return toClicking(e, state);
          }
        },
        up: function(e, state) {
          if (!isActive) {
            return toHover(e, state);
          }
        },
        moveOut: function(e, state) {
          if (!isActive) {
            return toNormal(e, state);
          }
        },
        dragOut: function(e, state) {
          if (!isActive) {
            return toNormal(e, state);
          }
        },
        click: function(e, state) {
          if (!isActive) {
            return click(e, state);
          }
        }
      });
      // Set up click handling
      attachClick = function(cb) {
        return handlers.push(cb);
      };
      if (props.click != null) {
        attachClick(props.click);
      }
      Take("SceneReady", function() {
        if (props.active) {
          return click();
        }
      });
      return scope = {
        click: attachClick,
        input: input,
        enable: function(v) {
          input.enable(v);
          if (v === false && !isActive) {
            return toNormal();
          }
        },
        doClick: click, // Trigger a click from outside code
        _highlight: function(enable) {
          if (highlighting = enable) {
            SVG.attrs(label, {
              fill: "black"
            });
          } else {
            SVG.attrs(label, {
              fill: labelFill
            });
          }
          return tickBG(curBG);
        }
      };
    });
  });

}).call(this);
